package org.filteredpush.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.6
 * 2016-07-18T15:55:41.659-04:00
 * Generated source version: 3.0.6
 * 
 */
@WebServiceClient(name = "AccessPointPortService", 
                  wsdlLocation = "file:/home/lowery/IdeaProjects/FP-Akka/src/main/resources/accesspoint.wsdl",
                  targetNamespace = "http://filteredpush.org/ws") 
public class AccessPointPortService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://filteredpush.org/ws", "AccessPointPortService");
    public final static QName AccessPointPortSoap11 = new QName("http://filteredpush.org/ws", "AccessPointPortSoap11");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/lowery/IdeaProjects/FP-Akka/src/main/resources/accesspoint.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AccessPointPortService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/lowery/IdeaProjects/FP-Akka/src/main/resources/accesspoint.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AccessPointPortService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AccessPointPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccessPointPortService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AccessPointPortService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AccessPointPortService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AccessPointPortService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns AccessPointPort
     */
    @WebEndpoint(name = "AccessPointPortSoap11")
    public AccessPointPort getAccessPointPortSoap11() {
        return super.getPort(AccessPointPortSoap11, AccessPointPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccessPointPort
     */
    @WebEndpoint(name = "AccessPointPortSoap11")
    public AccessPointPort getAccessPointPortSoap11(WebServiceFeature... features) {
        return super.getPort(AccessPointPortSoap11, AccessPointPort.class, features);
    }

}
